# Generated by Django 5.0.7 on 2024-08-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='alvo',
            new_name='profissional',
        ),
    ]
