# Generated by Django 5.0.7 on 2024-08-15 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_rename_autor_comentario_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
