# Generated by Django 5.0.7 on 2024-08-20 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacoes", "0004_avaliacao_delete_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="nota",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
