# Generated by Django 5.0.7 on 2024-08-20 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacoes", "0005_alter_avaliacao_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="nota",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
