# Generated by Django 5.0.7 on 2024-08-20 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0006_alter_agendamento_options_agendamento_created_at"),
        ("avaliacoes", "0006_alter_avaliacao_nota"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="agendamento",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                to="agendamentos.agendamento",
            ),
            preserve_default=False,
        ),
    ]
