# Generated by Django 5.0.7 on 2024-08-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Concluido", "Concluido"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Pendente",
                max_length=9,
            ),
        ),
    ]
