# Generated by Django 5.0.7 on 2024-08-16 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0003_horario_profissional"),
    ]

    operations = [
        migrations.RenameField(
            model_name="horario",
            old_name="data",
            new_name="data_fim",
        ),
        migrations.AddField(
            model_name="horario",
            name="data_fim_recorrencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="horario",
            name="data_inicio",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="horario",
            name="dias_semana",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="horario",
            name="frequencia",
            field=models.CharField(
                choices=[
                    ("NENHUMA", "Sem repetição"),
                    ("DIARIA", "Diariamente"),
                    ("SEMANAL", "Semanalmente"),
                    ("MENSAL", "Mensalmente"),
                ],
                default="NENHUMA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="horario",
            name="intervalo",
            field=models.IntegerField(default=1),
        ),
    ]
