# Generated by Django 5.0.7 on 2024-08-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0004_rename_data_horario_data_fim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horario",
            name="intervalo",
        ),
        migrations.AlterField(
            model_name="horario",
            name="frequencia",
            field=models.CharField(
                choices=[
                    ("UNICA", "Não se repete"),
                    ("DIARIA", "Todos os dias"),
                    ("SEMANAL", "Semanalmente"),
                    ("MENSAL", "Mensalmente"),
                ],
                default="UNICA",
                max_length=10,
            ),
        ),
    ]
