# Generated by Django 5.0.7 on 2024-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissional",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
