# Generated by Django 5.0.7 on 2024-08-13 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_profissional_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profissional",
            options={"verbose_name_plural": "Profissionais"},
        ),
    ]
