# Generated by Django 5.0.7 on 2024-08-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_alter_profissional_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissional",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
