# Generated by Django 5.0.7 on 2024-08-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_profissional_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='users/%y/%m/%d'),
        ),
    ]
